# Generated by Django 6.1 on 2026-08-22 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('importance_weight', models.PositiveSmallIntegerField(default=50)),
                ('current_satisfaction', models.PositiveSmallIntegerField(default=50)),
                ('desired_satisfaction', models.PositiveSmallIntegerField(default=80)),
                ('weekly_hours_target', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_areas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifeAreaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('satisfaction', models.PositiveSmallIntegerField()),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('life_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='life.lifearea')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('importance_weight', models.PositiveSmallIntegerField(default=50)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('IDEA', 'Idea'), ('ACTIVE', 'Activo'), ('PAUSED', 'Pausado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('life_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='life.lifearea')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='life.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_impacts', to='life.plan')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='life.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='plans',
            field=models.ManyToManyField(related_name='tasks', through='life.TaskImpact', to='life.plan'),
        ),
        migrations.CreateModel(
            name='WeeklyTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_total', models.PositiveIntegerField(default=0)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('progress_change', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tracking', to='life.plan')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
