# Generated by Django 6.1 on 2026-08-24 09:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_alter_lifearea_current_satisfaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifeareasnapshot',
            options={'ordering': ['-week']},
        ),
        migrations.AlterModelOptions(
            name='weeklytracking',
            options={'ordering': ['-week']},
        ),
        migrations.RenameField(
            model_name='lifeareasnapshot',
            old_name='satisfaction',
            new_name='satisfaction_end',
        ),
        migrations.RenameField(
            model_name='weeklytracking',
            old_name='consistency_score',
            new_name='progress_end',
        ),
        migrations.RemoveField(
            model_name='lifeareasnapshot',
            name='week_start',
        ),
        migrations.RemoveField(
            model_name='weeklytracking',
            name='progress_change',
        ),
        migrations.RemoveField(
            model_name='weeklytracking',
            name='tasks_completed',
        ),
        migrations.RemoveField(
            model_name='weeklytracking',
            name='tasks_total',
        ),
        migrations.RemoveField(
            model_name='weeklytracking',
            name='week_start',
        ),
        migrations.AddField(
            model_name='lifeareasnapshot',
            name='satisfaction_start',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklytracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklytracking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklytracking',
            name='progress_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lifeareasnapshot',
            name='hours_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weeklytracking',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='weeklytracking',
            name='planned_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('available_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overall_satisfaction_start', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_satisfaction_end', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lifeareasnapshot',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_snapshots', to='life.week'),
        ),
        migrations.AddField(
            model_name='weeklytracking',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_trackings', to='life.week'),
        ),
    ]
