# Generated by Django 6.1 on 2026-08-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_alter_lifeareasnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeareasnapshot',
            name='week',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_snapshots', to='life.week'),
        ),
        migrations.AlterField(
            model_name='weeklytracking',
            name='week',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_trackings', to='life.week'),
        ),
    ]
