# Generated by Django 6.1 on 2026-08-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_alter_lifeareasnapshot_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='planning_mode',
            field=models.CharField(choices=[('PASSIVE', 'Sin planificación'), ('MANUAL', 'Planificación manual'), ('OPTIMIZED', 'Optimizada')], default='PASSIVE', max_length=20),
        ),
    ]
