# Generated by Django 6.1 on 2026-08-24 21:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_week_planning_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTaskAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_hours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_allocations', to='life.task')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_allocations', to='life.week')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('week', 'task'), name='unique_task_allocation_per_week')],
            },
        ),
    ]
