# Generated by Django 6.1 on 2026-08-24 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_weeklytaskallocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklytaskallocation',
            options={'ordering': ['planned_date', 'task__due_date']},
        ),
        migrations.RemoveConstraint(
            model_name='weeklytaskallocation',
            name='unique_task_allocation_per_week',
        ),
        migrations.AddField(
            model_name='weeklytaskallocation',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklytaskallocation',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='weeklytaskallocation',
            constraint=models.UniqueConstraint(fields=('week', 'task', 'planned_date'), name='unique_task_allocation_per_day'),
        ),
    ]
