# Generated by Django 6.1 on 2026-08-25 14:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0007_alter_weeklytaskallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='include_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='include_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklytaskallocation',
            name='source',
            field=models.CharField(choices=[('OPTIMIZED', 'Planificador'), ('MANUAL', 'Manual')], default='OPTIMIZED', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklytaskallocation',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))]),
        ),
        migrations.CreateModel(
            name='WeeklyTaskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('included', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='life.task')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to='life.week')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('week', 'task'), name='unique_weekly_task_plan')],
            },
        ),
    ]
