# Generated by Django 6.1 on 2026-08-29 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_week_include_saturday_week_include_sunday_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklytaskplan',
            name='unique_weekly_task_plan',
        ),
        migrations.RemoveField(
            model_name='week',
            name='include_saturday',
        ),
        migrations.RemoveField(
            model_name='week',
            name='include_sunday',
        ),
        migrations.RemoveField(
            model_name='weeklytaskallocation',
            name='source',
        ),
        migrations.AlterField(
            model_name='weeklytaskallocation',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='WeeklyTaskPlan',
        ),
    ]
